const CASE_PARTICLES = [
  {
    tag: 'case.gen',
    tibetan: 'གི / ཀྱི / གྱི',
    name: '属格',
    pinyin: 'gyi / kyi / gyis',
    function: '表示所属关系',
    chinese: '的',
    english: "of (possessive)",
    example: 'བོད་གི་ཡུལ་',
    example_meaning: '西藏的地域',
    example_note: 'བོད་（西藏）+ གི + ཡུལ་（地方）',
  },
  {
    tag: 'case.agn',
    tibetan: 'གྱིས',
    name: '作格（施格）',
    pinyin: 'gyis',
    function: '表示施事或工具',
    chinese: '由…（做）',
    english: 'by (agent)',
    example: 'སློབ་དཔོན་གྱིས་བོད་ནས་ཆོས་སྐུལ་བཏང་',
    example_meaning: '上师从西藏发出了教言',
    example_note: 'སློབ་དཔོན་（上师）+ གྱིས + བོད་ནས་（从西藏）+ ...',
  },
  {
    tag: 'case.all',
    tibetan: 'ལ',
    name: '为格（与格）',
    pinyin: 'la',
    function: '表示间接宾语或目的',
    chinese: '对 / 给 / 为',
    english: 'to / for (dative)',
    example: 'བོད་གི་ཡུལ་ལྷོ་ལ་སོང་',
    example_meaning: '去西藏的南部',
    example_note: 'ཡུལ་ལྷོ་（南方的地域）+ ལ + སོང་（去，命令式）',
  },
  {
    tag: 'case.abl',
    tibetan: 'ལས',
    name: '离格',
    pinyin: 'las',
    function: '表示离开或起点',
    chinese: '从 / 离',
    english: 'from / away (ablative)',
    example: 'བོད་ལས་བསྡམ་',
    example_meaning: '从西藏分离',
    example_note: 'བོད་（西藏）+ ལས + བསྡམ་（分开）',
  },
  {
    tag: 'case.ela',
    tibetan: 'ནས',
    name: '从格',
    pinyin: 'nas',
    function: '表示从某处出发',
    chinese: '从…起',
    english: 'from (elative)',
    example: 'དགའ་ལན་ནས་',
    example_meaning: '从加兰（出发）',
    example_note: 'དགའ་ལན་（加兰）+ ནས',
  },
  {
    tag: 'case.ass',
    tibetan: 'དང',
    name: '共同格',
    pinyin: 'dang',
    function: '表示共同或伴随',
    chinese: '与 / 和 / 同',
    english: 'with / together (associative)',
    example: 'བདག་དང་མཉམ་དུ',
    example_meaning: '与我一起',
    example_note: 'བདག་（我）+ དང + མཉམ་དུ + 一起',
  },
  {
    tag: 'case.term',
    tibetan: 'དུ / ར',
    name: '终结格',
    pinyin: 'du / ru',
    function: '表示到达点或方向',
    chinese: '至 / 向',
    english: 'to / until (terminative)',
    example: 'བོད་དུ་སོང་',
    example_meaning: '去到西藏',
    example_note: 'བོད་（西藏）+ དུ + སོང་（去）',
  },
  {
    tag: 'case.loc',
    tibetan: 'ན',
    name: '处格',
    pinyin: 'na',
    function: '表示场所或位置',
    chinese: '在',
    english: 'at / in (locative)',
    example: 'ཕྱི་ནང་གི་ཆོས་སྡེ་ན་',
    example_meaning: '在内外法教之中',
    example_note: 'ཕྱི་ནང་（内外）+ གི་ཆོས་སྡེ་（法教）+ ན',
  },
  {
    tag: 'case.comp',
    tibetan: 'ལྟར',
    name: '比格',
    pinyin: 'btar',
    function: '表示比较',
    chinese: '比',
    english: 'than (comparative)',
    example: 'དགའ་བས་ལྟར',
    example_meaning: '比喜更多',
    example_note: 'དགའ་（喜）+ བས + ལྟར',
  },
  {
    tag: 'case.nare',
    tibetan: 'ན་རེ',
    name: '连格（属-处格）',
    pinyin: 'na re',
    function: '表示连接或序列',
    chinese: '则 / 然后',
    english: 'then / and then',
    example: 'གསོལ་ན་རེ',
    example_meaning: '若祈祷则…',
    example_note: 'གསོལ་（祈祷）+ ན་རེ + 条件句连词',
  },
];

export { CASE_PARTICLES };
